import os
import pickle
import warnings
from typing import Any, Iterable

import numpy as np
import torch
import torch.nn as nn
from transformers import AutoModel, AutoTokenizer

warnings.filterwarnings("ignore")


class TextEmbeddingModel(nn.Module):
    """
    Local copy of the DeTeCtive embedding model interface.

    Upstream source: https://github.com/heyongxin233/DeTeCtive
    """

    def __init__(self, model_name: str, output_hidden_states: bool = False):
        super().__init__()
        self.model_name = model_name
        self.model = AutoModel.from_pretrained(
            model_name,
            trust_remote_code=True,
            output_hidden_states=output_hidden_states,
        )
        self.tokenizer = AutoTokenizer.from_pretrained(model_name)

    def pooling(
        self,
        model_output: torch.Tensor,
        attention_mask: torch.Tensor,
        use_pooling: str = "average",
        hidden_states: bool = False,
    ) -> torch.Tensor:
        if hidden_states:
            model_output.masked_fill(~attention_mask[None, ..., None].bool(), 0.0)
            if use_pooling == "average":
                emb = model_output.sum(dim=2) / attention_mask.sum(dim=1)[..., None]
            else:
                emb = model_output[:, :, 0]
            return emb.permute(1, 0, 2)

        model_output.masked_fill(~attention_mask[..., None].bool(), 0.0)
        if use_pooling == "average":
            emb = model_output.sum(dim=1) / attention_mask.sum(dim=1)[..., None]
        elif use_pooling == "cls":
            emb = model_output[:, 0]
        else:
            raise ValueError(f"Unsupported pooling method: {use_pooling}")
        return emb

    def forward(
        self,
        encoded_batch: dict[str, torch.Tensor],
        use_pooling: str = "average",
        hidden_states: bool = False,
    ) -> torch.Tensor:
        if "t5" in self.model_name.lower():
            input_ids = encoded_batch["input_ids"]
            decoder_input_ids = torch.zeros(
                (input_ids.shape[0], 1),
                dtype=torch.long,
                device=input_ids.device,
            )
            model_output = self.model(**encoded_batch, decoder_input_ids=decoder_input_ids)
        else:
            model_output = self.model(**encoded_batch)

        if "bge" in self.model_name.lower() or "mxbai" in self.model_name.lower():
            use_pooling = "cls"
        if isinstance(model_output, tuple):
            model_output = model_output[0]
        if isinstance(model_output, dict):
            if hidden_states:
                model_output = torch.stack(model_output["hidden_states"], dim=0)
            else:
                model_output = model_output["last_hidden_state"]
        elif hasattr(model_output, "last_hidden_state"):
            if hidden_states:
                model_output = torch.stack(model_output.hidden_states, dim=0)
            else:
                model_output = model_output.last_hidden_state

        emb = self.pooling(model_output, encoded_batch["attention_mask"], use_pooling, hidden_states)
        return torch.nn.functional.normalize(emb, dim=-1)


class DeTeCtiveDetector:
    """
    DeTeCtive KNN detector with the same predict_batch interface as DeBERTaDetector.

    The returned score is the share of K nearest neighbors labelled as AI-generated.
    DeTeCtive's upstream inference treats label 0 as AI-generated by default.
    """

    def __init__(
        self,
        model_path: str | None = None,
        database_path: str | None = None,
        model_name: str | None = None,
        k: int | None = None,
        embedding_dim: int | None = None,
        ai_label: str | int | None = None,
    ):
        self.model_path = model_path or os.getenv(
            "DETECTIVE_MODEL_PATH",
            "models/detective/DeTeCtive/Deepfake_best.pth",
        )
        self.database_path = database_path or os.getenv(
            "DETECTIVE_DATABASE_PATH",
            "models/detective/DeTeCtive/database/deepfake",
        )
        self.model_name = model_name or os.getenv(
            "DETECTIVE_MODEL_NAME",
            "princeton-nlp/unsup-simcse-roberta-base",
        )
        self.k = int(k or os.getenv("DETECTIVE_K", "5"))
        self.embedding_dim = int(embedding_dim or os.getenv("DETECTIVE_EMBEDDING_DIM", "768"))
        self.ai_label = str(ai_label if ai_label is not None else os.getenv("DETECTIVE_AI_LABEL", "0"))
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

        self._validate_paths()
        self.faiss = self._import_faiss()

        print(f"Loading DeTeCtive embedding model from: {self.model_path}")
        print(f"Loading DeTeCtive FAISS database from: {self.database_path}")
        print(f"Using device: {self.device}")

        self.model = TextEmbeddingModel(self.model_name).to(self.device)
        self.tokenizer = self.model.tokenizer
        self._load_checkpoint(self.model_path)
        self.model.eval()

        self.index, self.index_id_to_db_id = self._load_index(self.database_path)
        self.label_dict = self._load_pickle(os.path.join(self.database_path, "label_dict.pkl"))
        print("DeTeCtive model and database loaded successfully.")

    def predict_batch(self, texts: list[str], batch_size: int = 32) -> list[float]:
        valid_indices = [i for i, text in enumerate(texts) if text and isinstance(text, str) and text.strip()]
        valid_texts = [texts[i] for i in valid_indices]
        final_scores = [0.0] * len(texts)

        if not valid_texts:
            return final_scores

        scored_texts: list[float] = []
        for start in range(0, len(valid_texts), batch_size):
            batch_texts = valid_texts[start:start + batch_size]
            embeddings = self._embed_texts(batch_texts)
            scores, indexes = self.index.search(embeddings.astype("float32"), self.k)

            for row_indexes, row_scores in zip(indexes, scores):
                labels = []
                for internal_index, _score in zip(row_indexes, row_scores):
                    if internal_index < 0:
                        continue
                    db_id = self.index_id_to_db_id[int(internal_index)]
                    labels.append(self._label_for_db_id(db_id))

                if not labels:
                    scored_texts.append(0.0)
                    continue
                ai_votes = sum(1 for label in labels if str(label) == self.ai_label)
                scored_texts.append(float(ai_votes / len(labels)))

        for idx, score in zip(valid_indices, scored_texts):
            final_scores[idx] = score
        return final_scores

    def _embed_texts(self, texts: list[str]) -> np.ndarray:
        encoded_text = self.tokenizer.batch_encode_plus(
            texts,
            return_tensors="pt",
            max_length=512,
            padding="max_length",
            truncation=True,
        )
        encoded_text = {key: value.to(self.device) for key, value in encoded_text.items()}
        with torch.no_grad():
            embeddings = self.model(encoded_text)
        return embeddings.cpu().detach().numpy()

    def _validate_paths(self) -> None:
        if not os.path.isfile(self.model_path):
            raise FileNotFoundError(
                f"DeTeCtive checkpoint not found at '{self.model_path}'. "
                "Set DETECTIVE_MODEL_PATH to a downloaded DeTeCtive .pth checkpoint."
            )

        required_database_files = ["index.faiss", "index_meta.faiss", "label_dict.pkl"]
        missing_files = [
            filename
            for filename in required_database_files
            if not os.path.isfile(os.path.join(self.database_path, filename))
        ]
        if missing_files:
            raise FileNotFoundError(
                f"DeTeCtive database at '{self.database_path}' is missing: {missing_files}. "
                "Set DETECTIVE_DATABASE_PATH to a generated DeTeCtive FAISS database."
            )

    @staticmethod
    def _import_faiss() -> Any:
        try:
            import faiss

            return faiss
        except ImportError as exc:
            raise ImportError(
                "DeTeCtive requires FAISS. Install faiss-gpu on the cluster, "
                "or faiss-cpu if GPU FAISS is unavailable."
            ) from exc

    @staticmethod
    def _load_pickle(path: str) -> Any:
        with open(path, "rb") as file:
            return pickle.load(file)

    def _load_checkpoint(self, model_path: str) -> None:
        checkpoint = torch.load(model_path, map_location=self.device)
        state_dict = self._extract_state_dict(checkpoint)
        model_keys = set(self.model.state_dict().keys())

        variants = [
            state_dict,
            self._strip_prefix(state_dict, "module."),
            self._strip_prefix(state_dict, "model."),
            self._add_prefix(state_dict, "model."),
        ]
        variants = self._dedupe_state_dicts(variants)
        best_state = max(variants, key=lambda item: len(model_keys.intersection(item.keys())))

        if not model_keys.intersection(best_state.keys()):
            raise RuntimeError("Could not match any DeTeCtive checkpoint keys to the embedding model.")

        load_result = self.model.load_state_dict(best_state, strict=False)
        if load_result.missing_keys or load_result.unexpected_keys:
            print(
                "Loaded DeTeCtive checkpoint with non-strict key matching "
                f"({len(load_result.missing_keys)} missing, {len(load_result.unexpected_keys)} unexpected)."
            )

    @staticmethod
    def _extract_state_dict(checkpoint: Any) -> dict[str, torch.Tensor]:
        if isinstance(checkpoint, dict):
            for key in ("state_dict", "model_state_dict", "model"):
                nested = checkpoint.get(key)
                if isinstance(nested, dict):
                    return nested
            return checkpoint
        raise TypeError("Unsupported DeTeCtive checkpoint format.")

    @staticmethod
    def _strip_prefix(state_dict: dict[str, torch.Tensor], prefix: str) -> dict[str, torch.Tensor]:
        return {
            key[len(prefix):] if key.startswith(prefix) else key: value
            for key, value in state_dict.items()
        }

    @staticmethod
    def _add_prefix(state_dict: dict[str, torch.Tensor], prefix: str) -> dict[str, torch.Tensor]:
        return {
            key if key.startswith(prefix) else f"{prefix}{key}": value
            for key, value in state_dict.items()
        }

    @staticmethod
    def _dedupe_state_dicts(
        state_dicts: Iterable[dict[str, torch.Tensor]],
    ) -> list[dict[str, torch.Tensor]]:
        seen = set()
        unique_state_dicts = []
        for state_dict in state_dicts:
            signature = tuple(state_dict.keys())
            if signature in seen:
                continue
            seen.add(signature)
            unique_state_dicts.append(state_dict)
        return unique_state_dicts

    def _load_index(self, database_path: str):
        index = self.faiss.read_index(os.path.join(database_path, "index.faiss"))
        if self.device.type == "cuda" and hasattr(self.faiss, "index_cpu_to_all_gpus"):
            index = self.faiss.index_cpu_to_all_gpus(index)

        with open(os.path.join(database_path, "index_meta.faiss"), "rb") as file:
            index_id_to_db_id = pickle.load(file)

        if len(index_id_to_db_id) != index.ntotal:
            raise ValueError("DeTeCtive FAISS index metadata length does not match index size.")
        return index, index_id_to_db_id

    def _label_for_db_id(self, db_id: Any) -> Any:
        candidates = [db_id, str(db_id)]
        try:
            candidates.append(int(db_id))
        except (TypeError, ValueError):
            pass

        for candidate in candidates:
            if candidate in self.label_dict:
                return self.label_dict[candidate]
        raise KeyError(f"Could not find DeTeCtive label for database id '{db_id}'.")
